CREATE SCHEMA IF NOT EXISTS bd_boletas;

CREATE TABLE IF NOT EXISTS bd_boletas.boleta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio_boleta VARCHAR(100) NOT NULL,
    glosa_boleta VARCHAR(255),
    tipo_boleta VARCHAR(50) NOT NULL,
    fecha_emision_boleta DATE NOT NULL,
    monto_bruto_boleta INTEGER NOT NULL,
    monto_neto_boleta INTEGER NOT NULL,
    estado_boleta VARCHAR(50) NOT NULL
);